package net.mocury.stardewravine.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricModelProvider;
import net.minecraft.data.client.BlockStateModelGenerator;
import net.minecraft.data.client.ItemModelGenerator;
import net.minecraft.data.client.Models;
import net.minecraft.data.client.TexturedModel;
import net.minecraft.item.ArmorItem;
import net.mocury.stardewravine.block.ModBlocks;
import net.mocury.stardewravine.block.custom.*;
import net.mocury.stardewravine.item.ModItems;

public class ModModelProvider extends FabricModelProvider {
    public ModModelProvider(FabricDataOutput output) {
        super(output);
    }

    @Override
    public void generateBlockStateModels(BlockStateModelGenerator blockStateModelGenerator) {
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.AQUAMARINE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.TOPAZ_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.JADE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RUBY_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PRISMATIC_SHARD_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RADIONITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RAW_RADIONITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.NETHER_RADIONITE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.AQUAMARINE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.AQUAMARINE_DEEPSLATE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.TOPAZ_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.TOPAZ_DEEPSLATE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.NETHER_TOPAZ_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.JADE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.JADE_DEEPSLATE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RUBY_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RUBY_DEEPSLATE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.NETHER_RUBY_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.REFINED_QUARTZ_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.IRIDIUM_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.IRIDIUM_DEEPSLATE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.NETHER_IRIDIUM_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PEARL_BLOCK);
        BlockStateModelGenerator.BlockTexturePool esperitePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.ESPERITE);
        BlockStateModelGenerator.BlockTexturePool polishedEsperitePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.POLISHED_ESPERITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SMOOTH_ESPERITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ESPERITE_BRICKS);
        BlockStateModelGenerator.BlockTexturePool marblePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.MARBLE);
        BlockStateModelGenerator.BlockTexturePool polishedMarblePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.POLISHED_MARBLE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SMOOTH_MARBLE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MARBLE_BRICKS);
        BlockStateModelGenerator.BlockTexturePool soapstonePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SOAPSTONE);
        BlockStateModelGenerator.BlockTexturePool polishedSoapstonePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.POLISHED_SOAPSTONE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SMOOTH_SOAPSTONE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SOAPSTONE_BRICKS);
        BlockStateModelGenerator.BlockTexturePool limestonePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.LIMESTONE);
        BlockStateModelGenerator.BlockTexturePool polishedLimestonePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.POLISHED_LIMESTONE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SMOOTH_LIMESTONE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIMESTONE_BRICKS);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BUDDING_CINDER_SHARD_BLOCK);
        BlockStateModelGenerator.BlockTexturePool fireQuartzPool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.FIRE_QUARTZ_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SMOOTH_FIRE_QUARTZ_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.FIRE_QUARTZ_BRICKS);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.FIRE_QUARTZ_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_HELVINE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LEMON_STONE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_LEMON_STONE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.TIGERS_EYE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_TIGERS_EYE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.KYANITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_KYANITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PYRITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_PYRITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.FLUORAPATITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_FLUORAPATITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.JAGOITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_JAGOITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CELESTINE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_CELESTINE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GEMINITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_GEMINITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.JASPER_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_JASPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.AERINITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_AERINITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORPIMENT_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_ORPIMENT);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.DOLOMITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_DOLOMITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.JAMBORITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_JAMBORITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.NEKOITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_NEKOITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.NEPTUNITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_NEPTUNITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LUNARITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_LUNARITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.END_LUNARITE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RAW_HEMATITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.REFINED_HEMATITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MALACHITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CALCITE_MALACHITE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIMESTONE_MALACHITE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.OPAL_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SMOOTH_OPAL_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.OPAL_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.DEEPSLATE_OPAL_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.END_OPAL_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.FIRE_OPAL_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SMOOTH_FIRE_OPAL_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.NETHER_FIRE_OPAL_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.DEEPSLATE_FIRE_OPAL_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.END_FIRE_OPAL_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MARBLE_LAPIS_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIMESTONE_LAPIS_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PYRITE_LAPIS_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GEODE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.DEEPSLATE_GEODE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.FROZEN_GEODE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.DEEPSLATE_FROZEN_GEODE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.END_FROZEN_GEODE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.NETHER_MAGMA_GEODE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACKSTONE_MAGMA_GEODE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BASALT_MAGMA_GEODE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.DEEPSLATE_OMNI_GEODE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.END_OMNI_GEODE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.NETHER_OMNI_GEODE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BLACKSTONE_OMNI_GEODE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BASALT_OMNI_GEODE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.FAIRY_STONE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.END_FAIRY_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.TERRASINE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_TERRASINE);

        blockStateModelGenerator.registerSingleton(ModBlocks.POLISHED_MALACHITE, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.SCROLL_BLOCK, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.RED_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.ORANGE_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.YELLOW_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.LIME_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.GREEN_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.CYAN_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.LIGHT_BLUE_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.BLUE_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.PURPLE_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.MAGENTA_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.PINK_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.WHITE_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.LIGHT_GRAY_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.GRAY_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.BLACK_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.BROWN_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.BIXITE, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.POLISHED_BIXITE, TexturedModel.CUBE_COLUMN);

        blockStateModelGenerator.registerAmethyst(ModBlocks.CINDER_CLUSTER);
        blockStateModelGenerator.registerAmethyst(ModBlocks.LARGE_CINDER_BUD);
        blockStateModelGenerator.registerAmethyst(ModBlocks.MEDIUM_CINDER_BUD);
        blockStateModelGenerator.registerAmethyst(ModBlocks.SMALL_CINDER_BUD);

        blockStateModelGenerator.registerFlowerPotPlant(ModBlocks.FAIRY_ROSE, ModBlocks.POTTED_FAIRY_ROSE, BlockStateModelGenerator.TintType.NOT_TINTED);
        blockStateModelGenerator.registerFlowerPotPlant(ModBlocks.BLUE_JAZZ, ModBlocks.POTTED_BLUE_JAZZ, BlockStateModelGenerator.TintType.NOT_TINTED);
        blockStateModelGenerator.registerFlowerPotPlant(ModBlocks.CROCUS, ModBlocks.POTTED_CROCUS, BlockStateModelGenerator.TintType.NOT_TINTED);
        blockStateModelGenerator.registerFlowerPotPlant(ModBlocks.SWEET_PEA, ModBlocks.POTTED_SWEET_PEA, BlockStateModelGenerator.TintType.NOT_TINTED);
        blockStateModelGenerator.registerFlowerPotPlant(ModBlocks.DAFFODIL, ModBlocks.POTTED_DAFFODIL, BlockStateModelGenerator.TintType.NOT_TINTED);
        blockStateModelGenerator.registerFlowerPotPlant(ModBlocks.SUMMER_SPANGLE, ModBlocks.POTTED_SUMMER_SPANGLE, BlockStateModelGenerator.TintType.NOT_TINTED);
        blockStateModelGenerator.registerDoubleBlock(ModBlocks.AMARANTH, BlockStateModelGenerator.TintType.NOT_TINTED);
        blockStateModelGenerator.registerDoubleBlock(ModBlocks.FAIRY_ROSE_BUSH, BlockStateModelGenerator.TintType.NOT_TINTED);

        esperitePool.stairs(ModBlocks.ESPERITE_STAIRS);
        esperitePool.slab(ModBlocks.ESPERITE_SLAB);
        esperitePool.wall(ModBlocks.ESPERITE_WALL);
        polishedEsperitePool.stairs(ModBlocks.POLISHED_ESPERITE_STAIRS);
        polishedEsperitePool.slab(ModBlocks.POLISHED_ESPERITE_SLAB);
        polishedEsperitePool.wall(ModBlocks.POLISHED_ESPERITE_WALL);
        marblePool.stairs(ModBlocks.MARBLE_STAIRS);
        marblePool.slab(ModBlocks.MARBLE_SLAB);
        marblePool.wall(ModBlocks.MARBLE_WALL);
        polishedMarblePool.stairs(ModBlocks.POLISHED_MARBLE_STAIRS);
        polishedMarblePool.slab(ModBlocks.POLISHED_MARBLE_SLAB);
        polishedMarblePool.wall(ModBlocks.POLISHED_MARBLE_WALL);
        soapstonePool.stairs(ModBlocks.SOAPSTONE_STAIRS);
        soapstonePool.slab(ModBlocks.SOAPSTONE_SLAB);
        soapstonePool.wall(ModBlocks.SOAPSTONE_WALL);
        polishedSoapstonePool.stairs(ModBlocks.POLISHED_SOAPSTONE_STAIRS);
        polishedSoapstonePool.slab(ModBlocks.POLISHED_SOAPSTONE_SLAB);
        polishedSoapstonePool.wall(ModBlocks.POLISHED_SOAPSTONE_WALL);
        limestonePool.stairs(ModBlocks.LIMESTONE_STAIRS);
        limestonePool.slab(ModBlocks.LIMESTONE_SLAB);
        limestonePool.wall(ModBlocks.LIMESTONE_WALL);
        polishedLimestonePool.stairs(ModBlocks.POLISHED_LIMESTONE_STAIRS);
        polishedLimestonePool.slab(ModBlocks.POLISHED_LIMESTONE_SLAB);
        polishedLimestonePool.wall(ModBlocks.POLISHED_LIMESTONE_WALL);
        fireQuartzPool.stairs(ModBlocks.FIRE_QUARTZ_STAIRS);
        fireQuartzPool.slab(ModBlocks.FIRE_QUARTZ_SLAB);

        blockStateModelGenerator.registerCrop(ModBlocks.MIXED_CROP, MixedCropBlock.AGE, 0, 1, 2, 3);
        blockStateModelGenerator.registerCrop(ModBlocks.GARLIC_CROP, GarlicCropBlock.AGE, 0, 1, 2, 3, 4);
        blockStateModelGenerator.registerCrop(ModBlocks.LEEK_CROP, LeekCropBlock.AGE, 0, 1, 2, 3);
        blockStateModelGenerator.registerCrop(ModBlocks.SPRING_ONION_CROP, SpringOnionCropBlock.AGE, 0, 1, 2, 3);
        blockStateModelGenerator.registerCrop(ModBlocks.PARSNIP_CROP, ParsnipCropBlock.AGE, 0, 1, 2, 3, 4, 5);
        blockStateModelGenerator.registerCrop(ModBlocks.HORSERADISH_CROP, HorseradishCropBlock.AGE, 0, 1, 2, 3);
        blockStateModelGenerator.registerCrop(ModBlocks.RHUBARB_CROP, RhubarbCropBlock.AGE, 0, 1, 2, 3, 4, 5);
        blockStateModelGenerator.registerCrop(ModBlocks.KALE_CROP, KaleCropBlock.AGE, 0, 1, 2, 3, 4);
        blockStateModelGenerator.registerCrop(ModBlocks.CAULIFLOWER_CROP, CauliflowerCropBlock.AGE, 0, 1, 2, 3, 4, 5);
        blockStateModelGenerator.registerCrop(ModBlocks.GREEN_BEAN_CROP, GreenBeanCropBlock.AGE, 0, 1, 2, 3, 4, 5);
        blockStateModelGenerator.registerCrop(ModBlocks.RICE_CROP, RiceCropBlock.AGE, 0, 1, 2, 3, 4);

        blockStateModelGenerator.registerTintableCrossBlockStateWithStages(ModBlocks.BLUEBERRY_BUSH, BlockStateModelGenerator.TintType.NOT_TINTED,
                BlueberryBushBlock.AGE, 0, 1, 2, 3, 4);
        blockStateModelGenerator.registerTintableCrossBlockStateWithStages(ModBlocks.SALMONBERRY_BUSH, BlockStateModelGenerator.TintType.NOT_TINTED,
                SalmonberryBushBlock.AGE, 0, 1, 2, 3);
        blockStateModelGenerator.registerTintableCrossBlockStateWithStages(ModBlocks.STRAWBERRY_BUSH, BlockStateModelGenerator.TintType.NOT_TINTED,
                StrawberryBushBlock.AGE, 0, 1, 2, 3, 4, 5);
        blockStateModelGenerator.registerTintableCrossBlockStateWithStages(ModBlocks.COFFEE_BUSH, BlockStateModelGenerator.TintType.NOT_TINTED,
                CoffeeBushBlock.AGE, 0, 1, 2, 3, 4, 5);


        blockStateModelGenerator.registerLog(ModBlocks.MAPLE_LOG).log(ModBlocks.MAPLE_LOG).wood(ModBlocks.MAPLE_WOOD);
        blockStateModelGenerator.registerLog(ModBlocks.STRIPPED_MAPLE_LOG).log(ModBlocks.STRIPPED_MAPLE_LOG).wood(ModBlocks.STRIPPED_MAPLE_WOOD);
        BlockStateModelGenerator.BlockTexturePool maplePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.MAPLE_PLANKS);
        blockStateModelGenerator.registerSingleton(ModBlocks.MAPLE_LEAVES, TexturedModel.LEAVES);
        blockStateModelGenerator.registerTintableCrossBlockState(ModBlocks.MAPLE_SAPLING, BlockStateModelGenerator.TintType.NOT_TINTED);
        maplePool.stairs(ModBlocks.MAPLE_STAIRS);
        maplePool.slab(ModBlocks.MAPLE_SLAB);
        maplePool.pressurePlate(ModBlocks.MAPLE_PRESSURE_PLATE);
        maplePool.button(ModBlocks.MAPLE_BUTTON);
        maplePool.fence(ModBlocks.MAPLE_FENCE);
        maplePool.fenceGate(ModBlocks.MAPLE_FENCE_GATE);
        blockStateModelGenerator.registerDoor(ModBlocks.MAPLE_DOOR);
        blockStateModelGenerator.registerTrapdoor(ModBlocks.MAPLE_TRAPDOOR);

        blockStateModelGenerator.registerLog(ModBlocks.MYSTIC_LOG).log(ModBlocks.MYSTIC_LOG).wood(ModBlocks.MYSTIC_WOOD);
        blockStateModelGenerator.registerLog(ModBlocks.STRIPPED_MYSTIC_LOG).log(ModBlocks.STRIPPED_MYSTIC_LOG).wood(ModBlocks.STRIPPED_MYSTIC_WOOD);
        BlockStateModelGenerator.BlockTexturePool mysticPool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.MYSTIC_PLANKS);
        blockStateModelGenerator.registerSingleton(ModBlocks.MYSTIC_LEAVES, TexturedModel.LEAVES);
        blockStateModelGenerator.registerTintableCrossBlockState(ModBlocks.MYSTIC_SAPLING, BlockStateModelGenerator.TintType.NOT_TINTED);
        mysticPool.stairs(ModBlocks.MYSTIC_STAIRS);
        mysticPool.slab(ModBlocks.MYSTIC_SLAB);
        mysticPool.pressurePlate(ModBlocks.MYSTIC_PRESSURE_PLATE);
        mysticPool.button(ModBlocks.MYSTIC_BUTTON);
        mysticPool.fence(ModBlocks.MYSTIC_FENCE);
        mysticPool.fenceGate(ModBlocks.MYSTIC_FENCE_GATE);
        blockStateModelGenerator.registerDoor(ModBlocks.MYSTIC_DOOR);
        blockStateModelGenerator.registerTrapdoor(ModBlocks.MYSTIC_TRAPDOOR);

        blockStateModelGenerator.registerLog(ModBlocks.APRICOT_LOG).log(ModBlocks.APRICOT_LOG).wood(ModBlocks.APRICOT_WOOD);
        blockStateModelGenerator.registerLog(ModBlocks.STRIPPED_APRICOT_LOG).log(ModBlocks.STRIPPED_APRICOT_LOG).wood(ModBlocks.STRIPPED_APRICOT_WOOD);
        BlockStateModelGenerator.BlockTexturePool apricotPool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.APRICOT_PLANKS);
        blockStateModelGenerator.registerSingleton(ModBlocks.APRICOT_LEAVES, TexturedModel.LEAVES);
        blockStateModelGenerator.registerTintableCrossBlockState(ModBlocks.APRICOT_SAPLING, BlockStateModelGenerator.TintType.NOT_TINTED);
        apricotPool.stairs(ModBlocks.APRICOT_STAIRS);
        apricotPool.slab(ModBlocks.APRICOT_SLAB);
        apricotPool.pressurePlate(ModBlocks.APRICOT_PRESSURE_PLATE);
        apricotPool.button(ModBlocks.APRICOT_BUTTON);
        apricotPool.fence(ModBlocks.APRICOT_FENCE);
        apricotPool.fenceGate(ModBlocks.APRICOT_FENCE_GATE);
        blockStateModelGenerator.registerDoor(ModBlocks.APRICOT_DOOR);
        blockStateModelGenerator.registerTrapdoor(ModBlocks.APRICOT_TRAPDOOR);

        blockStateModelGenerator.registerLog(ModBlocks.ORANGE_LOG).log(ModBlocks.ORANGE_LOG).wood(ModBlocks.ORANGE_WOOD);
        blockStateModelGenerator.registerLog(ModBlocks.STRIPPED_ORANGE_LOG).log(ModBlocks.STRIPPED_ORANGE_LOG).wood(ModBlocks.STRIPPED_ORANGE_WOOD);
        BlockStateModelGenerator.BlockTexturePool orangePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.ORANGE_PLANKS);
        blockStateModelGenerator.registerSingleton(ModBlocks.ORANGE_LEAVES, TexturedModel.LEAVES);
        blockStateModelGenerator.registerTintableCrossBlockState(ModBlocks.ORANGE_SAPLING, BlockStateModelGenerator.TintType.NOT_TINTED);
        orangePool.stairs(ModBlocks.ORANGE_STAIRS);
        orangePool.slab(ModBlocks.ORANGE_SLAB);
        orangePool.pressurePlate(ModBlocks.ORANGE_PRESSURE_PLATE);
        orangePool.button(ModBlocks.ORANGE_BUTTON);
        orangePool.fence(ModBlocks.ORANGE_FENCE);
        orangePool.fenceGate(ModBlocks.ORANGE_FENCE_GATE);
        blockStateModelGenerator.registerDoor(ModBlocks.ORANGE_DOOR);
        blockStateModelGenerator.registerTrapdoor(ModBlocks.ORANGE_TRAPDOOR);

        blockStateModelGenerator.registerLog(ModBlocks.POMEGRANATE_LOG).log(ModBlocks.POMEGRANATE_LOG).wood(ModBlocks.POMEGRANATE_WOOD);
        blockStateModelGenerator.registerLog(ModBlocks.STRIPPED_POMEGRANATE_LOG).log(ModBlocks.STRIPPED_POMEGRANATE_LOG).wood(ModBlocks.STRIPPED_POMEGRANATE_WOOD);
        BlockStateModelGenerator.BlockTexturePool pomegranatePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.POMEGRANATE_PLANKS);
        blockStateModelGenerator.registerSingleton(ModBlocks.POMEGRANATE_LEAVES, TexturedModel.LEAVES);
        blockStateModelGenerator.registerTintableCrossBlockState(ModBlocks.POMEGRANATE_SAPLING, BlockStateModelGenerator.TintType.NOT_TINTED);
        pomegranatePool.stairs(ModBlocks.POMEGRANATE_STAIRS);
        pomegranatePool.slab(ModBlocks.POMEGRANATE_SLAB);
        pomegranatePool.pressurePlate(ModBlocks.POMEGRANATE_PRESSURE_PLATE);
        pomegranatePool.button(ModBlocks.POMEGRANATE_BUTTON);
        pomegranatePool.fence(ModBlocks.POMEGRANATE_FENCE);
        pomegranatePool.fenceGate(ModBlocks.POMEGRANATE_FENCE_GATE);
        blockStateModelGenerator.registerDoor(ModBlocks.POMEGRANATE_DOOR);
        blockStateModelGenerator.registerTrapdoor(ModBlocks.POMEGRANATE_TRAPDOOR);

        blockStateModelGenerator.registerLog(ModBlocks.MANGO_LOG).log(ModBlocks.MANGO_LOG).wood(ModBlocks.MANGO_WOOD);
        blockStateModelGenerator.registerLog(ModBlocks.STRIPPED_MANGO_LOG).log(ModBlocks.STRIPPED_MANGO_LOG).wood(ModBlocks.STRIPPED_MANGO_WOOD);
        BlockStateModelGenerator.BlockTexturePool mangoPool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.MANGO_PLANKS);
        blockStateModelGenerator.registerSingleton(ModBlocks.MANGO_LEAVES, TexturedModel.LEAVES);
        blockStateModelGenerator.registerTintableCrossBlockState(ModBlocks.MANGO_SAPLING, BlockStateModelGenerator.TintType.NOT_TINTED);
        mangoPool.stairs(ModBlocks.MANGO_STAIRS);
        mangoPool.slab(ModBlocks.MANGO_SLAB);
        mangoPool.pressurePlate(ModBlocks.MANGO_PRESSURE_PLATE);
        mangoPool.button(ModBlocks.MANGO_BUTTON);
        mangoPool.fence(ModBlocks.MANGO_FENCE);
        mangoPool.fenceGate(ModBlocks.MANGO_FENCE_GATE);
        blockStateModelGenerator.registerDoor(ModBlocks.MANGO_DOOR);
        blockStateModelGenerator.registerTrapdoor(ModBlocks.MANGO_TRAPDOOR);

        blockStateModelGenerator.registerLog(ModBlocks.BANANA_LOG).log(ModBlocks.BANANA_LOG).wood(ModBlocks.BANANA_WOOD);
        blockStateModelGenerator.registerLog(ModBlocks.STRIPPED_BANANA_LOG).log(ModBlocks.STRIPPED_BANANA_LOG).wood(ModBlocks.STRIPPED_BANANA_WOOD);
        BlockStateModelGenerator.BlockTexturePool bananaPool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.BANANA_PLANKS);
        blockStateModelGenerator.registerSingleton(ModBlocks.BANANA_LEAVES, TexturedModel.LEAVES);
        blockStateModelGenerator.registerTintableCrossBlockState(ModBlocks.BANANA_SAPLING, BlockStateModelGenerator.TintType.NOT_TINTED);
        bananaPool.stairs(ModBlocks.BANANA_STAIRS);
        bananaPool.slab(ModBlocks.BANANA_SLAB);
        bananaPool.pressurePlate(ModBlocks.BANANA_PRESSURE_PLATE);
        bananaPool.button(ModBlocks.BANANA_BUTTON);
        bananaPool.fence(ModBlocks.BANANA_FENCE);
        bananaPool.fenceGate(ModBlocks.BANANA_FENCE_GATE);
        blockStateModelGenerator.registerDoor(ModBlocks.BANANA_DOOR);
        blockStateModelGenerator.registerTrapdoor(ModBlocks.BANANA_TRAPDOOR);

        blockStateModelGenerator.registerLog(ModBlocks.PEACH_LOG).log(ModBlocks.PEACH_LOG).wood(ModBlocks.PEACH_WOOD);
        blockStateModelGenerator.registerLog(ModBlocks.STRIPPED_PEACH_LOG).log(ModBlocks.STRIPPED_PEACH_LOG).wood(ModBlocks.STRIPPED_PEACH_WOOD);
        BlockStateModelGenerator.BlockTexturePool peachPool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.PEACH_PLANKS);
        blockStateModelGenerator.registerSingleton(ModBlocks.PEACH_LEAVES, TexturedModel.LEAVES);
        blockStateModelGenerator.registerTintableCrossBlockState(ModBlocks.PEACH_SAPLING, BlockStateModelGenerator.TintType.NOT_TINTED);
        peachPool.stairs(ModBlocks.PEACH_STAIRS);
        peachPool.slab(ModBlocks.PEACH_SLAB);
        peachPool.pressurePlate(ModBlocks.PEACH_PRESSURE_PLATE);
        peachPool.button(ModBlocks.PEACH_BUTTON);
        peachPool.fence(ModBlocks.PEACH_FENCE);
        peachPool.fenceGate(ModBlocks.PEACH_FENCE_GATE);
        blockStateModelGenerator.registerDoor(ModBlocks.PEACH_DOOR);
        blockStateModelGenerator.registerTrapdoor(ModBlocks.PEACH_TRAPDOOR);

        blockStateModelGenerator.registerSingleton(ModBlocks.FRUITING_POMEGRANATE_LEAVES, TexturedModel.LEAVES);
        blockStateModelGenerator.registerSingleton(ModBlocks.FRUITING_ORANGE_LEAVES, TexturedModel.LEAVES);
        blockStateModelGenerator.registerSingleton(ModBlocks.FRUITING_APRICOT_LEAVES, TexturedModel.LEAVES);
        blockStateModelGenerator.registerSingleton(ModBlocks.FRUITING_CHERRY_LEAVES, TexturedModel.LEAVES);
        blockStateModelGenerator.registerSingleton(ModBlocks.FRUITING_MANGO_LEAVES, TexturedModel.LEAVES);
        blockStateModelGenerator.registerSingleton(ModBlocks.FRUITING_BANANA_LEAVES, TexturedModel.LEAVES);
        blockStateModelGenerator.registerSingleton(ModBlocks.FRUITING_PEACH_LEAVES, TexturedModel.LEAVES);

        blockStateModelGenerator.registerLog(ModBlocks.FIDDLEHEAD_LOG).log(ModBlocks.FIDDLEHEAD_LOG).wood(ModBlocks.FIDDLEHEAD_WOOD);
        blockStateModelGenerator.registerLog(ModBlocks.STRIPPED_FIDDLEHEAD_LOG).log(ModBlocks.STRIPPED_FIDDLEHEAD_LOG).wood(ModBlocks.STRIPPED_FIDDLEHEAD_WOOD);
        BlockStateModelGenerator.BlockTexturePool fiddleheadPool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.FIDDLEHEAD_PLANKS);
        blockStateModelGenerator.registerSingleton(ModBlocks.FIDDLEHEAD_LEAVES, TexturedModel.LEAVES);
        blockStateModelGenerator.registerTintableCrossBlockState(ModBlocks.FIDDLEHEAD_SAPLING, BlockStateModelGenerator.TintType.NOT_TINTED);
        fiddleheadPool.stairs(ModBlocks.FIDDLEHEAD_STAIRS);
        fiddleheadPool.slab(ModBlocks.FIDDLEHEAD_SLAB);
        fiddleheadPool.pressurePlate(ModBlocks.FIDDLEHEAD_PRESSURE_PLATE);
        fiddleheadPool.button(ModBlocks.FIDDLEHEAD_BUTTON);
        fiddleheadPool.fence(ModBlocks.FIDDLEHEAD_FENCE);
        fiddleheadPool.fenceGate(ModBlocks.FIDDLEHEAD_FENCE_GATE);
        blockStateModelGenerator.registerDoor(ModBlocks.FIDDLEHEAD_DOOR);
        blockStateModelGenerator.registerTrapdoor(ModBlocks.FIDDLEHEAD_TRAPDOOR);

        blockStateModelGenerator.registerSingleton(ModBlocks.PETRIFIED_SLIME_BLOCK, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GHOST_CRYSTAL_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GHOST_GLASS);

    }

    @Override
    public void generateItemModels(ItemModelGenerator itemModelGenerator) {
        itemModelGenerator.register(ModItems.AQUAMARINE, Models.GENERATED);
        itemModelGenerator.register(ModItems.TOPAZ, Models.GENERATED);
        itemModelGenerator.register(ModItems.JADE, Models.GENERATED);
        itemModelGenerator.register(ModItems.RUBY, Models.GENERATED);
        itemModelGenerator.register(ModItems.PRISMATIC_SHARD, Models.GENERATED);
        itemModelGenerator.register(ModItems.RADIONITE_INGOT, Models.GENERATED);
        itemModelGenerator.register(ModItems.RAW_RADIONITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.REFINED_QUARTZ, Models.GENERATED);
        itemModelGenerator.register(ModItems.IRIDIUM_INGOT, Models.GENERATED);
        itemModelGenerator.register(ModItems.RAW_IRIDIUM, Models.GENERATED);
        itemModelGenerator.register(ModItems.CINDER_SHARD, Models.GENERATED);
        itemModelGenerator.register(ModItems.PEARL, Models.GENERATED);
        itemModelGenerator.register(ModItems.FIRE_QUARTZ, Models.GENERATED);

        itemModelGenerator.register(ModItems.HELVINE, Models.GENERATED);
        itemModelGenerator.register(ModItems.LEMON_STONE, Models.GENERATED);
        itemModelGenerator.register(ModItems.TIGERS_EYE, Models.GENERATED);
        itemModelGenerator.register(ModItems.KYANITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.PYRITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.FLUORAPATITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.JAGOITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.CELESTINE, Models.GENERATED);
        itemModelGenerator.register(ModItems.GEMINITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.JASPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.AERINITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORPIMENT, Models.GENERATED);
        itemModelGenerator.register(ModItems.DOLOMITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.JAMBORITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.NEKOITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.NEPTUNITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.LUNARITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.MALACHITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.OPAL, Models.GENERATED);
        itemModelGenerator.register(ModItems.FIRE_OPAL, Models.GENERATED);
        itemModelGenerator.register(ModItems.FAIRY_STONE, Models.GENERATED);
        itemModelGenerator.register(ModItems.FAIRY_DUST, Models.GENERATED);

        itemModelGenerator.register(ModItems.GEODE, Models.GENERATED);
        itemModelGenerator.register(ModItems.FROZEN_GEODE, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGMA_GEODE, Models.GENERATED);
        itemModelGenerator.register(ModItems.OMNI_GEODE, Models.GENERATED);
        itemModelGenerator.register(ModItems.GEODE_SHELL, Models.GENERATED);
        itemModelGenerator.register(ModItems.FROZEN_GEODE_SHELL, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGMA_GEODE_SHELL, Models.GENERATED);
        itemModelGenerator.register(ModItems.OMNI_GEODE_SHELL, Models.GENERATED);

        itemModelGenerator.register(ModItems.FAIRY_BOX, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGIC_QUIVER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ICE_ROD, Models.HANDHELD);
        itemModelGenerator.register(ModItems.BASILISK_PAW, Models.GENERATED);
        itemModelGenerator.register(ModItems.RUSTY_SPUR, Models.GENERATED);
        itemModelGenerator.register(ModItems.GOLDEN_SPUR, Models.GENERATED);
        itemModelGenerator.register(ModItems.RUSTY_COG, Models.GENERATED);
        itemModelGenerator.register(ModItems.IRON_COG, Models.GENERATED);
        itemModelGenerator.register(ModItems.RUSTY_SPOON, Models.HANDHELD);
        itemModelGenerator.register(ModItems.SILVER_SPOON, Models.HANDHELD);
        itemModelGenerator.register(ModItems.DRIED_STARFISH, Models.GENERATED);

        itemModelGenerator.register(ModItems.BIXITE_CHUNK, Models.GENERATED);
        itemModelGenerator.register(ModItems.TERRASINE, Models.GENERATED);

        itemModelGenerator.register(ModItems.STARDROP, Models.GENERATED);
        itemModelGenerator.register(ModItems.ANCIENT_FRUIT, Models.GENERATED);
        itemModelGenerator.register(ModItems.GARLIC, Models.GENERATED);
        itemModelGenerator.register(ModItems.PARSNIP, Models.GENERATED);
        itemModelGenerator.register(ModItems.RHUBARB, Models.GENERATED);
        itemModelGenerator.register(ModItems.KALE, Models.GENERATED);
        itemModelGenerator.register(ModItems.CAULIFLOWER, Models.GENERATED);
        itemModelGenerator.register(ModItems.GREEN_BEAN, Models.GENERATED);
        itemModelGenerator.register(ModItems.RICE, Models.GENERATED);

        itemModelGenerator.register(ModItems.IRIDIUM_SWORD, Models.HANDHELD);
        itemModelGenerator.register(ModItems.IRIDIUM_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.IRIDIUM_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(ModItems.IRIDIUM_AXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.IRIDIUM_HOE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.NETHER_IRIDIUM_SWORD, Models.HANDHELD);
        itemModelGenerator.register(ModItems.NETHER_IRIDIUM_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.NETHER_IRIDIUM_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(ModItems.NETHER_IRIDIUM_AXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.NETHER_IRIDIUM_HOE, Models.HANDHELD);

        itemModelGenerator.registerArmor(((ArmorItem) ModItems.IRIDIUM_HELMET));
        itemModelGenerator.registerArmor(((ArmorItem) ModItems.IRIDIUM_CHESTPLATE));
        itemModelGenerator.registerArmor(((ArmorItem) ModItems.IRIDIUM_LEGGINGS));
        itemModelGenerator.registerArmor(((ArmorItem) ModItems.IRIDIUM_BOOTS));
        itemModelGenerator.registerArmor(((ArmorItem) ModItems.NETHER_IRIDIUM_HELMET));
        itemModelGenerator.registerArmor(((ArmorItem) ModItems.NETHER_IRIDIUM_CHESTPLATE));
        itemModelGenerator.registerArmor(((ArmorItem) ModItems.NETHER_IRIDIUM_LEGGINGS));
        itemModelGenerator.registerArmor(((ArmorItem) ModItems.NETHER_IRIDIUM_BOOTS));

        itemModelGenerator.register(ModBlocks.MAPLE_SAPLING.asItem(), Models.GENERATED);
        itemModelGenerator.register(ModBlocks.MYSTIC_SAPLING.asItem(), Models.GENERATED);
        itemModelGenerator.register(ModBlocks.APRICOT_SAPLING.asItem(), Models.GENERATED);
        itemModelGenerator.register(ModBlocks.ORANGE_SAPLING.asItem(), Models.GENERATED);
        itemModelGenerator.register(ModBlocks.POMEGRANATE_SAPLING.asItem(), Models.GENERATED);
        itemModelGenerator.register(ModBlocks.MANGO_SAPLING.asItem(), Models.GENERATED);
        itemModelGenerator.register(ModBlocks.BANANA_SAPLING.asItem(), Models.GENERATED);
        itemModelGenerator.register(ModBlocks.PEACH_SAPLING.asItem(), Models.GENERATED);
        itemModelGenerator.register(ModBlocks.FIDDLEHEAD_SAPLING.asItem(), Models.GENERATED);
        itemModelGenerator.register(ModItems.APRICOT, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORANGE, Models.GENERATED);
        itemModelGenerator.register(ModItems.POMEGRANATE, Models.GENERATED);
        itemModelGenerator.register(ModItems.MANGO, Models.GENERATED);
        itemModelGenerator.register(ModItems.BANANA, Models.GENERATED);
        itemModelGenerator.register(ModItems.PEACH, Models.GENERATED);
        itemModelGenerator.register(ModItems.CHERRIES, Models.GENERATED);
        itemModelGenerator.register(ModItems.SAP, Models.GENERATED);
        itemModelGenerator.register(ModItems.MYSTIC_SYRUP, Models.GENERATED);
        itemModelGenerator.register(ModItems.OAK_RESIN, Models.GENERATED);
        itemModelGenerator.register(ModItems.PINE_TAR, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAPLE_SYRUP, Models.GENERATED);
        itemModelGenerator.register(ModItems.PETRIFIED_SLIME, Models.GENERATED);
        itemModelGenerator.register(ModItems.GHOST_CRYSTAL, Models.GENERATED);
    }
}
