package net.mocury.stardewravine.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricModelProvider;
import net.minecraft.data.client.BlockStateModelGenerator;
import net.minecraft.data.client.ItemModelGenerator;
import net.minecraft.data.client.Models;
import net.minecraft.data.client.TexturedModel;
import net.minecraft.item.ArmorItem;
import net.minecraft.util.Identifier;
import net.mocury.stardewravine.block.ModBlocks;
import net.mocury.stardewravine.item.ModItems;

public class ModModelProvider extends FabricModelProvider {
    public ModModelProvider(FabricDataOutput output) {
        super(output);
    }

    @Override
    public void generateBlockStateModels(BlockStateModelGenerator blockStateModelGenerator) {
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.AQUAMARINE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.TOPAZ_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.JADE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RUBY_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PRISMATIC_SHARD_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RADIONITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RAW_RADIONITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.NETHER_RADIONITE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.AQUAMARINE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.AQUAMARINE_DEEPSLATE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.TOPAZ_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.TOPAZ_DEEPSLATE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.NETHER_TOPAZ_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.JADE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.JADE_DEEPSLATE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RUBY_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RUBY_DEEPSLATE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.NETHER_RUBY_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.REFINED_QUARTZ_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.IRIDIUM_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.IRIDIUM_DEEPSLATE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.NETHER_IRIDIUM_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PEARL_BLOCK);
        BlockStateModelGenerator.BlockTexturePool esperitePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.ESPERITE);
        BlockStateModelGenerator.BlockTexturePool polishedEsperitePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.POLISHED_ESPERITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SMOOTH_ESPERITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ESPERITE_BRICKS);
        BlockStateModelGenerator.BlockTexturePool marblePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.MARBLE);
        BlockStateModelGenerator.BlockTexturePool polishedMarblePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.POLISHED_MARBLE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SMOOTH_MARBLE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MARBLE_BRICKS);
        BlockStateModelGenerator.BlockTexturePool soapstonePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.SOAPSTONE);
        BlockStateModelGenerator.BlockTexturePool polishedSoapstonePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.POLISHED_SOAPSTONE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SMOOTH_SOAPSTONE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SOAPSTONE_BRICKS);
        BlockStateModelGenerator.BlockTexturePool limestonePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.LIMESTONE);
        BlockStateModelGenerator.BlockTexturePool polishedLimestonePool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.POLISHED_LIMESTONE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SMOOTH_LIMESTONE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIMESTONE_BRICKS);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.BUDDING_CINDER_SHARD_BLOCK);
        BlockStateModelGenerator.BlockTexturePool fireQuartzPool = blockStateModelGenerator.registerCubeAllModelTexturePool(ModBlocks.FIRE_QUARTZ_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SMOOTH_FIRE_QUARTZ_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.FIRE_QUARTZ_BRICKS);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.FIRE_QUARTZ_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_HELVINE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LEMON_STONE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_LEMON_STONE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.TIGERS_EYE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_TIGERS_EYE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.KYANITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_KYANITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.PYRITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_PYRITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.FLUORAPATITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_FLUORAPATITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.JAGOITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_JAGOITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CELESTINE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_CELESTINE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.GEMINITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_GEMINITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.JASPER_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_JASPER);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.AERINITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_AERINITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.ORPIMENT_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_ORPIMENT);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.DOLOMITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_DOLOMITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.JAMBORITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_JAMBORITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.NEKOITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_NEKOITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.NEPTUNITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_NEPTUNITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LUNARITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.POLISHED_LUNARITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.END_LUNARITE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.RAW_HEMATITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.REFINED_HEMATITE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.MALACHITE_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.CALCITE_MALACHITE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.LIMESTONE_MALACHITE_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.OPAL_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SMOOTH_OPAL_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.OPAL_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.DEEPSLATE_OPAL_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.END_OPAL_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.FIRE_OPAL_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.SMOOTH_FIRE_OPAL_BLOCK);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.NETHER_FIRE_OPAL_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.DEEPSLATE_FIRE_OPAL_ORE);
        blockStateModelGenerator.registerSimpleCubeAll(ModBlocks.END_FIRE_OPAL_ORE);

        blockStateModelGenerator.registerSingleton(ModBlocks.POLISHED_MALACHITE, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.SCROLL_BLOCK, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.RED_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.ORANGE_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.YELLOW_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.LIME_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.GREEN_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.CYAN_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.LIGHT_BLUE_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.BLUE_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.PURPLE_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.MAGENTA_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.PINK_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.WHITE_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.LIGHT_GRAY_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.GRAY_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.BLACK_SCROLL, TexturedModel.CUBE_COLUMN);
        blockStateModelGenerator.registerSingleton(ModBlocks.BROWN_SCROLL, TexturedModel.CUBE_COLUMN);

        blockStateModelGenerator.registerAmethyst(ModBlocks.CINDER_CLUSTER);
        blockStateModelGenerator.registerAmethyst(ModBlocks.LARGE_CINDER_BUD);
        blockStateModelGenerator.registerAmethyst(ModBlocks.MEDIUM_CINDER_BUD);
        blockStateModelGenerator.registerAmethyst(ModBlocks.SMALL_CINDER_BUD);

        esperitePool.stairs(ModBlocks.ESPERITE_STAIRS);
        esperitePool.slab(ModBlocks.ESPERITE_SLAB);
        esperitePool.wall(ModBlocks.ESPERITE_WALL);
        polishedEsperitePool.stairs(ModBlocks.POLISHED_ESPERITE_STAIRS);
        polishedEsperitePool.slab(ModBlocks.POLISHED_ESPERITE_SLAB);
        polishedEsperitePool.wall(ModBlocks.POLISHED_ESPERITE_WALL);
        marblePool.stairs(ModBlocks.MARBLE_STAIRS);
        marblePool.slab(ModBlocks.MARBLE_SLAB);
        marblePool.wall(ModBlocks.MARBLE_WALL);
        polishedMarblePool.stairs(ModBlocks.POLISHED_MARBLE_STAIRS);
        polishedMarblePool.slab(ModBlocks.POLISHED_MARBLE_SLAB);
        polishedMarblePool.wall(ModBlocks.POLISHED_MARBLE_WALL);
        soapstonePool.stairs(ModBlocks.SOAPSTONE_STAIRS);
        soapstonePool.slab(ModBlocks.SOAPSTONE_SLAB);
        soapstonePool.wall(ModBlocks.SOAPSTONE_WALL);
        polishedSoapstonePool.stairs(ModBlocks.POLISHED_SOAPSTONE_STAIRS);
        polishedSoapstonePool.slab(ModBlocks.POLISHED_SOAPSTONE_SLAB);
        polishedSoapstonePool.wall(ModBlocks.POLISHED_SOAPSTONE_WALL);
        limestonePool.stairs(ModBlocks.LIMESTONE_STAIRS);
        limestonePool.slab(ModBlocks.LIMESTONE_SLAB);
        limestonePool.wall(ModBlocks.LIMESTONE_WALL);
        polishedLimestonePool.stairs(ModBlocks.POLISHED_LIMESTONE_STAIRS);
        polishedLimestonePool.slab(ModBlocks.POLISHED_LIMESTONE_SLAB);
        polishedLimestonePool.wall(ModBlocks.POLISHED_LIMESTONE_WALL);
        fireQuartzPool.stairs(ModBlocks.FIRE_QUARTZ_STAIRS);
        fireQuartzPool.slab(ModBlocks.FIRE_QUARTZ_SLAB);
    }

    @Override
    public void generateItemModels(ItemModelGenerator itemModelGenerator) {
        itemModelGenerator.register(ModItems.AQUAMARINE, Models.GENERATED);
        itemModelGenerator.register(ModItems.TOPAZ, Models.GENERATED);
        itemModelGenerator.register(ModItems.JADE, Models.GENERATED);
        itemModelGenerator.register(ModItems.RUBY, Models.GENERATED);
        itemModelGenerator.register(ModItems.PRISMATIC_SHARD, Models.GENERATED);
        itemModelGenerator.register(ModItems.RADIONITE_INGOT, Models.GENERATED);
        itemModelGenerator.register(ModItems.RAW_RADIONITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.REFINED_QUARTZ, Models.GENERATED);
        itemModelGenerator.register(ModItems.IRIDIUM_INGOT, Models.GENERATED);
        itemModelGenerator.register(ModItems.RAW_IRIDIUM, Models.GENERATED);
        itemModelGenerator.register(ModItems.CINDER_SHARD, Models.GENERATED);
        itemModelGenerator.register(ModItems.PEARL, Models.GENERATED);
        itemModelGenerator.register(ModItems.FIRE_QUARTZ, Models.GENERATED);

        itemModelGenerator.register(ModItems.HELVINE, Models.GENERATED);
        itemModelGenerator.register(ModItems.LEMON_STONE, Models.GENERATED);
        itemModelGenerator.register(ModItems.TIGERS_EYE, Models.GENERATED);
        itemModelGenerator.register(ModItems.KYANITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.PYRITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.FLUORAPATITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.JAGOITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.CELESTINE, Models.GENERATED);
        itemModelGenerator.register(ModItems.GEMINITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.JASPER, Models.GENERATED);
        itemModelGenerator.register(ModItems.AERINITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.ORPIMENT, Models.GENERATED);
        itemModelGenerator.register(ModItems.DOLOMITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.JAMBORITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.NEKOITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.NEPTUNITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.LUNARITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.MALACHITE, Models.GENERATED);
        itemModelGenerator.register(ModItems.OPAL, Models.GENERATED);
        itemModelGenerator.register(ModItems.FIRE_OPAL, Models.GENERATED);

        itemModelGenerator.register(ModItems.FAIRY_BOX, Models.GENERATED);
        itemModelGenerator.register(ModItems.MAGIC_QUIVER, Models.GENERATED);
        itemModelGenerator.register(ModItems.ICE_ROD, Models.HANDHELD);
        itemModelGenerator.register(ModItems.BASILISK_PAW, Models.GENERATED);
        itemModelGenerator.register(ModItems.RUSTY_SPUR, Models.GENERATED);
        itemModelGenerator.register(ModItems.GOLDEN_SPUR, Models.GENERATED);
        itemModelGenerator.register(ModItems.RUSTY_COG, Models.GENERATED);
        itemModelGenerator.register(ModItems.IRON_COG, Models.GENERATED);
        itemModelGenerator.register(ModItems.RUSTY_SPOON, Models.HANDHELD);
        itemModelGenerator.register(ModItems.SILVER_SPOON, Models.HANDHELD);
        itemModelGenerator.register(ModItems.DRIED_STARFISH, Models.GENERATED);

        itemModelGenerator.register(ModItems.STARDROP, Models.GENERATED);
        itemModelGenerator.register(ModItems.ANCIENT_FRUIT, Models.GENERATED);

        itemModelGenerator.register(ModItems.IRIDIUM_SWORD, Models.HANDHELD);
        itemModelGenerator.register(ModItems.IRIDIUM_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.IRIDIUM_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(ModItems.IRIDIUM_AXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.IRIDIUM_HOE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.NETHER_IRIDIUM_SWORD, Models.HANDHELD);
        itemModelGenerator.register(ModItems.NETHER_IRIDIUM_PICKAXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.NETHER_IRIDIUM_SHOVEL, Models.HANDHELD);
        itemModelGenerator.register(ModItems.NETHER_IRIDIUM_AXE, Models.HANDHELD);
        itemModelGenerator.register(ModItems.NETHER_IRIDIUM_HOE, Models.HANDHELD);

        itemModelGenerator.registerArmor(((ArmorItem) ModItems.IRIDIUM_HELMET));
        itemModelGenerator.registerArmor(((ArmorItem) ModItems.IRIDIUM_CHESTPLATE));
        itemModelGenerator.registerArmor(((ArmorItem) ModItems.IRIDIUM_LEGGINGS));
        itemModelGenerator.registerArmor(((ArmorItem) ModItems.IRIDIUM_BOOTS));
        itemModelGenerator.registerArmor(((ArmorItem) ModItems.NETHER_IRIDIUM_HELMET));
        itemModelGenerator.registerArmor(((ArmorItem) ModItems.NETHER_IRIDIUM_CHESTPLATE));
        itemModelGenerator.registerArmor(((ArmorItem) ModItems.NETHER_IRIDIUM_LEGGINGS));
        itemModelGenerator.registerArmor(((ArmorItem) ModItems.NETHER_IRIDIUM_BOOTS));
    }
}
