package net.mocury.stardewravine.item;

import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;
import net.mocury.stardewravine.StardewRavine;
import net.mocury.stardewravine.block.ModBlocks;

public class ModItemGroups {
    public static final ItemGroup STARDEW_RAVINE_GROUP = Registry.register(Registries.ITEM_GROUP,
            Identifier.of(StardewRavine.MOD_ID, "stardew_ravine_items"),
            FabricItemGroup.builder().icon(() -> new ItemStack(ModItems.STARDROP))
                    .displayName(Text.translatable("itemgroup.stardewravine.stardew_ravine_items"))
                    .entries((displayContext, entries) -> {
                        entries.add(ModItems.STARDROP);
                        entries.add(ModItems.ANCIENT_FRUIT);
                        entries.add(ModItems.PRISMATIC_SHARD);
                        entries.add(ModBlocks.PRISMATIC_SHARD_BLOCK);
                        entries.add(ModItems.AQUAMARINE);
                        entries.add(ModBlocks.AQUAMARINE_BLOCK);
                        entries.add(ModBlocks.AQUAMARINE_ORE);
                        entries.add(ModBlocks.AQUAMARINE_DEEPSLATE_ORE);
                        entries.add(ModItems.TOPAZ);
                        entries.add(ModBlocks.TOPAZ_BLOCK);
                        entries.add(ModBlocks.TOPAZ_ORE);
                        entries.add(ModBlocks.TOPAZ_DEEPSLATE_ORE);
                        entries.add(ModBlocks.NETHER_TOPAZ_ORE);
                        entries.add(ModItems.JADE);
                        entries.add(ModBlocks.JADE_BLOCK);
                        entries.add(ModBlocks.JADE_ORE);
                        entries.add(ModBlocks.JADE_DEEPSLATE_ORE);
                        entries.add(ModItems.RUBY);
                        entries.add(ModBlocks.RUBY_BLOCK);
                        entries.add(ModBlocks.RUBY_ORE);
                        entries.add(ModBlocks.RUBY_DEEPSLATE_ORE);
                        entries.add(ModBlocks.NETHER_RUBY_ORE);
                        entries.add(ModItems.RADIONITE_INGOT);
                        entries.add(ModItems.RAW_RADIONITE);
                        entries.add(ModBlocks.RADIONITE_BLOCK);
                        entries.add(ModBlocks.RAW_RADIONITE_BLOCK);
                        entries.add(ModBlocks.NETHER_RADIONITE_ORE);
                        entries.add(ModItems.IRIDIUM_INGOT);
                        entries.add(ModItems.RAW_IRIDIUM);
                        entries.add(ModBlocks.IRIDIUM_BLOCK);
                        entries.add(ModBlocks.RAW_IRIDIUM_BLOCK);
                        entries.add(ModBlocks.IRIDIUM_DEEPSLATE_ORE);
                        entries.add(ModBlocks.NETHER_IRIDIUM_ORE);

                        entries.add(ModItems.IRIDIUM_SWORD);
                        entries.add(ModItems.IRIDIUM_PICKAXE);
                        entries.add(ModItems.IRIDIUM_SHOVEL);
                        entries.add(ModItems.IRIDIUM_AXE);
                        entries.add(ModItems.IRIDIUM_HOE);
                        entries.add(ModItems.IRIDIUM_HELMET);
                        entries.add(ModItems.IRIDIUM_CHESTPLATE);
                        entries.add(ModItems.IRIDIUM_LEGGINGS);
                        entries.add(ModItems.IRIDIUM_BOOTS);
                        entries.add(ModItems.NETHER_IRIDIUM_SWORD);
                        entries.add(ModItems.NETHER_IRIDIUM_PICKAXE);
                        entries.add(ModItems.NETHER_IRIDIUM_SHOVEL);
                        entries.add(ModItems.NETHER_IRIDIUM_AXE);
                        entries.add(ModItems.NETHER_IRIDIUM_HOE);
                        entries.add(ModItems.NETHER_IRIDIUM_HELMET);
                        entries.add(ModItems.NETHER_IRIDIUM_CHESTPLATE);
                        entries.add(ModItems.NETHER_IRIDIUM_LEGGINGS);
                        entries.add(ModItems.NETHER_IRIDIUM_BOOTS);

                        entries.add(ModItems.FIRE_QUARTZ);
                        entries.add(ModBlocks.FIRE_QUARTZ_ORE);
                        entries.add(ModBlocks.FIRE_QUARTZ_BLOCK);
                        entries.add(ModBlocks.SMOOTH_FIRE_QUARTZ_BLOCK);
                        entries.add(ModBlocks.FIRE_QUARTZ_BRICKS);
                        entries.add(ModBlocks.FIRE_QUARTZ_PILLAR);
                        entries.add(ModBlocks.CHISELED_FIRE_QUARTZ);
                        entries.add(ModBlocks.FIRE_QUARTZ_STAIRS);
                        entries.add(ModBlocks.FIRE_QUARTZ_SLAB);
                        entries.add(ModItems.REFINED_QUARTZ);

                        entries.add(ModBlocks.REFINED_QUARTZ_BLOCK);
                        entries.add(ModItems.FAIRY_BOX);
                        entries.add(ModItems.MAGIC_QUIVER);
                        entries.add(ModItems.BASILISK_PAW);
                        entries.add(ModItems.ICE_ROD);
                        entries.add(ModItems.RUSTY_SPUR);
                        entries.add(ModItems.GOLDEN_SPUR);
                        entries.add(ModItems.RUSTY_COG);
                        entries.add(ModItems.IRON_COG);
                        entries.add(ModItems.RUSTY_SPOON);
                        entries.add(ModItems.SILVER_SPOON);
                        entries.add(ModItems.DRIED_STARFISH);

                        entries.add(ModBlocks.ESPERITE);
                        entries.add(ModBlocks.ESPERITE_SLAB);
                        entries.add(ModBlocks.ESPERITE_STAIRS);
                        entries.add(ModBlocks.ESPERITE_WALL);
                        entries.add(ModBlocks.POLISHED_ESPERITE);
                        entries.add(ModBlocks.POLISHED_ESPERITE_SLAB);
                        entries.add(ModBlocks.POLISHED_ESPERITE_STAIRS);
                        entries.add(ModBlocks.POLISHED_ESPERITE_WALL);
                        entries.add(ModBlocks.SMOOTH_ESPERITE);
                        entries.add(ModBlocks.ESPERITE_BRICKS);
                        entries.add(ModBlocks.ESPERITE_PILLAR);
                        entries.add(ModBlocks.CHISELED_ESPERITE);
                        entries.add(ModBlocks.MARBLE);
                        entries.add(ModBlocks.MARBLE_SLAB);
                        entries.add(ModBlocks.MARBLE_STAIRS);
                        entries.add(ModBlocks.MARBLE_WALL);
                        entries.add(ModBlocks.POLISHED_MARBLE);
                        entries.add(ModBlocks.POLISHED_MARBLE_SLAB);
                        entries.add(ModBlocks.POLISHED_MARBLE_STAIRS);
                        entries.add(ModBlocks.POLISHED_MARBLE_WALL);
                        entries.add(ModBlocks.SMOOTH_MARBLE);
                        entries.add(ModBlocks.MARBLE_BRICKS);
                        entries.add(ModBlocks.MARBLE_PILLAR);
                        entries.add(ModBlocks.CHISELED_MARBLE);
                        entries.add(ModBlocks.SOAPSTONE);
                        entries.add(ModBlocks.SOAPSTONE_SLAB);
                        entries.add(ModBlocks.SOAPSTONE_STAIRS);
                        entries.add(ModBlocks.SOAPSTONE_WALL);
                        entries.add(ModBlocks.POLISHED_SOAPSTONE);
                        entries.add(ModBlocks.POLISHED_SOAPSTONE_SLAB);
                        entries.add(ModBlocks.POLISHED_SOAPSTONE_STAIRS);
                        entries.add(ModBlocks.POLISHED_SOAPSTONE_WALL);
                        entries.add(ModBlocks.SMOOTH_SOAPSTONE);
                        entries.add(ModBlocks.SOAPSTONE_BRICKS);
                        entries.add(ModBlocks.SOAPSTONE_PILLAR);
                        entries.add(ModBlocks.CHISELED_SOAPSTONE);
                        entries.add(ModBlocks.LIMESTONE);
                        entries.add(ModBlocks.LIMESTONE_SLAB);
                        entries.add(ModBlocks.LIMESTONE_STAIRS);
                        entries.add(ModBlocks.LIMESTONE_WALL);
                        entries.add(ModBlocks.POLISHED_LIMESTONE);
                        entries.add(ModBlocks.POLISHED_LIMESTONE_SLAB);
                        entries.add(ModBlocks.POLISHED_LIMESTONE_STAIRS);
                        entries.add(ModBlocks.POLISHED_LIMESTONE_WALL);
                        entries.add(ModBlocks.SMOOTH_LIMESTONE);
                        entries.add(ModBlocks.LIMESTONE_BRICKS);
                        entries.add(ModBlocks.LIMESTONE_PILLAR);
                        entries.add(ModBlocks.CHISELED_LIMESTONE);
                        entries.add(ModBlocks.SOAP_LIME_TILES);
                        entries.add(ModBlocks.LIME_SOAP_TILES);
                        entries.add(ModBlocks.SOAP_ESPER_TILES);
                        entries.add(ModBlocks.ESPER_SOAP_TILES);
                        entries.add(ModBlocks.SOAP_MARBLE_TILES);
                        entries.add(ModBlocks.MARBLE_SOAP_TILES);
                        entries.add(ModBlocks.MARBLE_LIME_TILES);
                        entries.add(ModBlocks.LIME_MARBLE_TILES);
                        entries.add(ModBlocks.MARBLE_ESPER_TILES);
                        entries.add(ModBlocks.ESPER_MARBLE_TILES);
                        entries.add(ModBlocks.LIME_ESPER_TILES);
                        entries.add(ModBlocks.ESPER_LIME_TILES);

                        entries.add(ModItems.CINDER_SHARD);
                        entries.add(ModBlocks.CINDER_SHARD_BLOCK);
                        entries.add(ModBlocks.BUDDING_CINDER_SHARD_BLOCK);
                        entries.add(ModBlocks.CINDER_CLUSTER);
                        entries.add(ModBlocks.LARGE_CINDER_BUD);
                        entries.add(ModBlocks.MEDIUM_CINDER_BUD);
                        entries.add(ModBlocks.SMALL_CINDER_BUD);
                        entries.add(ModBlocks.CINDER_SHARD_ORE);
                        entries.add(ModItems.PEARL);
                        entries.add(ModBlocks.PEARL_BLOCK);

                        entries.add(ModItems.HELVINE);
                        entries.add(ModBlocks.HELVINE_BLOCK);
                        entries.add(ModBlocks.POLISHED_HELVINE);
                        entries.add(ModItems.LEMON_STONE);
                        entries.add(ModBlocks.LEMON_STONE_BLOCK);
                        entries.add(ModBlocks.POLISHED_LEMON_STONE);
                        entries.add(ModItems.TIGERS_EYE);
                        entries.add(ModBlocks.TIGERS_EYE_BLOCK);
                        entries.add(ModBlocks.POLISHED_TIGERS_EYE);
                        entries.add(ModItems.KYANITE);
                        entries.add(ModBlocks.KYANITE_BLOCK);
                        entries.add(ModBlocks.POLISHED_KYANITE);
                        entries.add(ModItems.PYRITE);
                        entries.add(ModBlocks.PYRITE_BLOCK);
                        entries.add(ModBlocks.POLISHED_PYRITE);
                        entries.add(ModItems.FLUORAPATITE);
                        entries.add(ModBlocks.FLUORAPATITE_BLOCK);
                        entries.add(ModBlocks.POLISHED_FLUORAPATITE);
                        entries.add(ModItems.JAGOITE);
                        entries.add(ModBlocks.JAGOITE_BLOCK);
                        entries.add(ModBlocks.POLISHED_JAGOITE);
                        entries.add(ModItems.CELESTINE);
                        entries.add(ModBlocks.CELESTINE_BLOCK);
                        entries.add(ModBlocks.POLISHED_CELESTINE);
                        entries.add(ModItems.GEMINITE);
                        entries.add(ModBlocks.GEMINITE_BLOCK);
                        entries.add(ModBlocks.POLISHED_GEMINITE);
                        entries.add(ModItems.JASPER);
                        entries.add(ModBlocks.JASPER_BLOCK);
                        entries.add(ModBlocks.POLISHED_JASPER);
                        entries.add(ModItems.AERINITE);
                        entries.add(ModBlocks.AERINITE_BLOCK);
                        entries.add(ModBlocks.POLISHED_AERINITE);
                        entries.add(ModItems.ORPIMENT);
                        entries.add(ModBlocks.ORPIMENT_BLOCK);
                        entries.add(ModBlocks.POLISHED_ORPIMENT);
                        entries.add(ModItems.DOLOMITE);
                        entries.add(ModBlocks.DOLOMITE_BLOCK);
                        entries.add(ModBlocks.POLISHED_DOLOMITE);
                        entries.add(ModItems.JAMBORITE);
                        entries.add(ModBlocks.JAMBORITE_BLOCK);
                        entries.add(ModBlocks.POLISHED_JAMBORITE);
                        entries.add(ModItems.NEKOITE);
                        entries.add(ModBlocks.NEKOITE_BLOCK);
                        entries.add(ModBlocks.POLISHED_NEKOITE);
                        entries.add(ModItems.NEPTUNITE);
                        entries.add(ModBlocks.NEPTUNITE_BLOCK);
                        entries.add(ModBlocks.POLISHED_NEPTUNITE);
                        entries.add(ModItems.LUNARITE);
                        entries.add(ModBlocks.LUNARITE_BLOCK);
                        entries.add(ModBlocks.POLISHED_LUNARITE);
                        entries.add(ModBlocks.END_LUNARITE_ORE);
                        entries.add(ModBlocks.RAW_HEMATITE);
                        entries.add(ModBlocks.REFINED_HEMATITE);
                        entries.add(ModBlocks.HEMATITE_ROSE);
                        entries.add(ModBlocks.DESERT_ROSE);
                        entries.add(ModItems.MALACHITE);
                        entries.add(ModBlocks.MALACHITE_BLOCK);
                        entries.add(ModBlocks.POLISHED_MALACHITE);
                        entries.add(ModBlocks.CALCITE_MALACHITE_ORE);
                        entries.add(ModBlocks.LIMESTONE_MALACHITE_ORE);

                        entries.add(ModBlocks.LIMESTONE_LAPIS_ORE);
                        entries.add(ModBlocks.MARBLE_LAPIS_ORE);
                        entries.add(ModBlocks.PYRITE_LAPIS_ORE);

                        entries.add(ModItems.OPAL);
                        entries.add(ModBlocks.OPAL_BLOCK);
                        entries.add(ModBlocks.SMOOTH_OPAL_BLOCK);
                        entries.add(ModBlocks.OPAL_BONE_BLOCK);
                        entries.add(ModBlocks.OPAL_ORE);
                        entries.add(ModBlocks.DEEPSLATE_OPAL_ORE);
                        entries.add(ModBlocks.END_OPAL_ORE);
                        entries.add(ModItems.FIRE_OPAL);
                        entries.add(ModBlocks.FIRE_OPAL_BLOCK);
                        entries.add(ModBlocks.SMOOTH_FIRE_OPAL_BLOCK);
                        entries.add(ModBlocks.FIRE_OPAL_BONE_BLOCK);
                        entries.add(ModBlocks.NETHER_FIRE_OPAL_ORE);
                        entries.add(ModBlocks.DEEPSLATE_FIRE_OPAL_ORE);
                        entries.add(ModBlocks.END_FIRE_OPAL_ORE);

                        entries.add(ModBlocks.SCROLL_BLOCK);
                        entries.add(ModBlocks.RED_SCROLL);
                        entries.add(ModBlocks.ORANGE_SCROLL);
                        entries.add(ModBlocks.YELLOW_SCROLL);
                        entries.add(ModBlocks.LIME_SCROLL);
                        entries.add(ModBlocks.GREEN_SCROLL);
                        entries.add(ModBlocks.CYAN_SCROLL);
                        entries.add(ModBlocks.LIGHT_BLUE_SCROLL);
                        entries.add(ModBlocks.BLUE_SCROLL);
                        entries.add(ModBlocks.PURPLE_SCROLL);
                        entries.add(ModBlocks.MAGENTA_SCROLL);
                        entries.add(ModBlocks.PINK_SCROLL);
                        entries.add(ModBlocks.WHITE_SCROLL);
                        entries.add(ModBlocks.LIGHT_GRAY_SCROLL);
                        entries.add(ModBlocks.GRAY_SCROLL);
                        entries.add(ModBlocks.BLACK_SCROLL);
                        entries.add(ModBlocks.BROWN_SCROLL);

                    }).build());


    public static void registerItemGroups() {
        StardewRavine.LOGGER.info("Registering Item Groups for " + StardewRavine.MOD_ID);
    }
}
